MLFLOW_HOST=0.0.0.0
MLFLOW_PORT=${MLFLOW_PORT}
MLFLOW_BACKEND_STORE_URI=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
MLFLOW_ARTIFACT_ROOT=s3://${MINIO_BUCKET}/${MLFLOW_ARTIFACT_PATH}
